---
engines:
  duplication:
    enabled: true
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
    checks:
      import/no-unresolved:
          enabled: false
  fixme:
    enabled: true
ratings:
  paths:
  - "src/**/*"
exclude_paths:
  - "webpack/*"
  - "node_modules/**/*"
  - "build/**/*"
  - "bin/*"
  - "flow-typed/**/*"
